logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
        descriptor: TRACE

spring:
  application:
    name: CinemaTickets-Movies
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cinema_tickets_movies?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql:3306/cinema_tickets_movies?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    password: ${db_password:}
    username: ${db_username:root}

  sql:
    init:
      mode: never

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSuperSecretKeyThatIsAtLeast32Chars}

server:
  port: 8081